### ISSUE TITLE
[RFE] Use elasticsearch-dsl in fmatch

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/py-commons#17]
The [elasticsearch-dsl library](https://elasticsearch-dsl.readthedocs.io/en/latest/) provides a higher-level series of helpers that makes easier to execute complex queries. By using this library we can reduce the complexity of the code, perform more complex queries and be less error prone

cc @shashank-boyapally

**Comment by shashank-boyapally** [comment]
This would be a great start towards code readabilty and a reducing errors. Will look into it and incorporate it. Thank you!!
